import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../providers/auth_provider.dart';
import '../providers/link_provider.dart';
import '../providers/collection_provider.dart';
import '../providers/ui_state_provider.dart';
import '../services/firebase_storage_service.dart';
import '../services/openrouter_service.dart';
import '../theme/void_colors.dart';
import '../utils/i18n.dart';
import '../screens/home_screen.dart';
import '../screens/favorites_screen.dart';
import '../screens/tags_screen.dart';
import '../screens/add_link_screen.dart';
import '../screens/options_screen.dart';

class MainScaffold extends StatefulWidget {
  const MainScaffold({super.key});

  @override
  State<MainScaffold> createState() => _MainScaffoldState();
}

class _MainScaffoldState extends State<MainScaffold> {
  int _selectedIndex = 0;

  static const List<Widget> _screens = [
    HomeScreen(),
    FavoritesScreen(),
    TagsScreen(),
  ];

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      await Future.wait([
        context.read<LinkProvider>().loadLinks(),
        context.read<CollectionProvider>().loadCollections(),
      ]);
      if (mounted) {
        _maybeAutoGenerateDescriptions();
      }
    });
  }

  Future<void> _maybeAutoGenerateDescriptions() async {
    final prefs = await SharedPreferences.getInstance();
    final lastRun = prefs.getString('lastAutoDescDate') ?? '';
    final today = DateTime.now().toIso8601String().substring(0, 10);
    if (lastRun == today) return;

    String apiKey = prefs.getString('openrouter_api_key') ?? '';
    String model = prefs.getString('openrouter_model') ??
        'meta-llama/llama-3.2-3b-instruct:free';

    // Prefer Firestore settings if logged in (cross-device sync)
    if (mounted) {
      final authState = context.read<AuthProvider>();
      if (authState.isLoggedIn && authState.user != null) {
        try {
          final remote = await FirebaseStorageService().getUserSettings(authState.user!.uid);
          if (remote['openrouterApiKey'] is String && (remote['openrouterApiKey'] as String).isNotEmpty) {
            apiKey = remote['openrouterApiKey'] as String;
          }
          if (remote['openrouterModel'] is String && (remote['openrouterModel'] as String).isNotEmpty) {
            model = remote['openrouterModel'] as String;
          }
        } catch (_) {}
      }
    }

    if (apiKey.isEmpty) return;

    await prefs.setString('lastAutoDescDate', today);

    if (!mounted) return;
    final provider = context.read<LinkProvider>();
    final pending =
        provider.links.where((l) => (l.aiDescription ?? '').isEmpty).toList();
    final service = OpenRouterService(apiKey: apiKey, model: model);

    for (final link in pending) {
      if (!mounted) break;
      try {
        final desc =
            await service.generateDescription(url: link.url, title: link.title);
        if (desc != null && desc.isNotEmpty && mounted) {
          await provider.updateLink(link.copyWith(aiDescription: desc));
        }
      } catch (_) {
        // skip silently
      }
    }
  }

  Future<void> _openAddLink() async {
    final result = await Navigator.push<bool>(
      context,
      MaterialPageRoute(builder: (_) => const AddLinkScreen()),
    );
    if (result == true && mounted) {
      context.read<LinkProvider>().loadLinks();
    }
  }

  @override
  Widget build(BuildContext context) {
    final selectMode = context.watch<UiStateProvider>().selectModeActive;

    final fab = Container(
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(28),
        boxShadow: const [
          BoxShadow(
            color: Color(0x80F5A623), // amber glow, 50% opacity
            blurRadius: 16,
            offset: Offset(0, 4),
          ),
        ],
      ),
      child: FloatingActionButton(
        onPressed: _openAddLink,
        tooltip: t('nav.addLink'),
        backgroundColor: VoidColors.darkAccent,
        foregroundColor: VoidColors.accentOnPrimary,
        elevation: 0,
        child: const Icon(Icons.add),
      ),
    );

    return Scaffold(
      body: IndexedStack(
        index: _selectedIndex,
        children: _screens,
      ),
      floatingActionButton: selectMode ? null : fab,
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      bottomNavigationBar: AnimatedSize(
        duration: const Duration(milliseconds: 200),
        curve: Curves.easeInOut,
        child: selectMode
            ? const SizedBox(width: double.infinity, height: 0)
            : BottomAppBar(
            color: VoidColors.darkBgElevated,
            elevation: 0,
            shape: const CircularNotchedRectangle(),
            notchMargin: 8.0,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: [
                _NavItem(
                  icon: Icons.home_outlined,
                  selectedIcon: Icons.home,
                  label: t('nav.home'),
                  selected: _selectedIndex == 0,
                  onTap: () => setState(() => _selectedIndex = 0),
                ),
                _NavItem(
                  icon: Icons.star_border,
                  selectedIcon: Icons.star,
                  label: t('nav.favorites'),
                  selected: _selectedIndex == 1,
                  onTap: () => setState(() => _selectedIndex = 1),
                ),
                const SizedBox(width: 56), // spazio per il FAB
                _NavItem(
                  icon: Icons.label_outline,
                  selectedIcon: Icons.label,
                  label: t('nav.tags'),
                  selected: _selectedIndex == 2,
                  onTap: () => setState(() => _selectedIndex = 2),
                ),
                _NavItem(
                  icon: Icons.person_outline,
                  selectedIcon: Icons.person,
                  label: t('options.title'),
                  selected: false,
                  onTap: () => Navigator.push(
                    context,
                    MaterialPageRoute(builder: (_) => const OptionsScreen()),
                  ),
                ),
              ],
            ),
          ),
        ),
    );
  }
}

class _NavItem extends StatelessWidget {
  final IconData icon;
  final IconData selectedIcon;
  final String label;
  final bool selected;
  final VoidCallback onTap;

  const _NavItem({
    required this.icon,
    required this.selectedIcon,
    required this.label,
    required this.selected,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    // Icon: amber when active, tertiary when inactive.
    // Label: always text-primary — never amber.
    const activeIconColor = VoidColors.darkAccent;
    const inactiveIconColor = VoidColors.darkTextTertiary;
    const labelColor = VoidColors.darkTextPrimary;
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              selected ? selectedIcon : icon,
              color: selected ? activeIconColor : inactiveIconColor,
            ),
            const SizedBox(height: 2),
            Text(
              label,
              style: const TextStyle(
                fontSize: 11,
                color: labelColor,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
