// File generated by FlutterFire CLI.
// To regenerate this file, run `flutterfire configure` from the project root.

import 'dart:io';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    if (Platform.isIOS) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9sUgJPMHUFs0h95Wg-oqrVZjg0H8LPDs',
    appId: '1:30821726892:android:71f5ba8e91b92cb2e9bd09',
    messagingSenderId: '30821726892',
    projectId: 'voidpocket-97ae7',
    databaseURL: 'https://voidpocket-97ae7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'voidpocket-97ae7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9sUgJPMHUFs0h95Wg-oqrVZjg0H8LPDs',
    appId: '1:30821726892:ios:71f5ba8e91b92cb2e9bd09',
    messagingSenderId: '30821726892',
    projectId: 'voidpocket-97ae7',
    databaseURL: 'https://voidpocket-97ae7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'voidpocket-97ae7.firebasestorage.app',
    iosBundleId: 'com.voidpocket.app',
  );
}
